server:
  port: 8082

spring:
  application:
    name: api-gateway
  profiles:
    active: local
  cloud:
    config:
      import: optional:configserver:http://localhost:8888
      uri: http://localhost:8888