server:
  port: 9090
  servlet:
    context-path: /admin

spring:
  application:
    admin:
      name: admin-service
  profiles:
    active: local
  cloud:
    config:
      import: optional:configserver:http://localhost:8888
      uri: http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"