server:
  port: 8083

spring:
  application:
    name: chat-service
  profiles:
    active: local
  cloud:
    config:
      import: optional:configserver:http://localhost:8888
      uri: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops
