server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ethan-bros/chatting-microservice-config-server.git #설정 파일 저장할 git 저장소
          default-label: main
          search-paths: '.' #'{application}'
  config:
    import: optional:configwerver:http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"